import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

export type ReportPeriod = "daily" | "weekly" | "monthly";

export type ReportItemEntry = {
  date: string;
  intensityLabel: string | null;
  remark: string | null;
};

export type ReportDomainSection = {
  name: string;
  completionRate: number;
  items: {
    name: string;
    completedCount: number;
    scheduledCount: number;
    entries: ReportItemEntry[];
  }[];
};

export type CareReportData = {
  appName: string;
  displayName: string;
  period: ReportPeriod;
  startDate: string;
  endDate: string;
  overallScore: number;
  overallRate: number;
  domains: ReportDomainSection[];
};

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1f1f1f",
  },
  title: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: "#666",
    marginBottom: 16,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
    padding: 10,
    backgroundColor: "#fff7ed",
  },
  domainTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    marginTop: 12,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e5e5",
  },
  details: {
    paddingTop: 8,
    paddingBottom: 4,
  },
  detail: {
    fontSize: 9,
    color: "#555",
    marginBottom: 2,
  },
  item: {
    marginBottom: 2,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    fontSize: 9,
    color: "#888",
  },
});

function periodLabel(period: ReportPeriod): string {
  if (period === "daily") return "Daily";
  if (period === "weekly") return "Weekly";
  return "Monthly";
}

function ReportEntryLines({
  entry,
  showDate,
}: {
  entry: ReportItemEntry;
  showDate: boolean;
}) {
  const intensityText = entry.intensityLabel
    ? showDate
      ? `${entry.date} · ${entry.intensityLabel}`
      : `Intensity: ${entry.intensityLabel}`
    : showDate && entry.remark
      ? entry.date
      : null;

  return (
    <View>
      {intensityText ? (
        <Text style={styles.detail}>{intensityText}</Text>
      ) : null}
      {entry.remark ? (
        <Text style={styles.detail}>Remark: {entry.remark}</Text>
      ) : null}
    </View>
  );
}

export function CareReportDocument({ data }: { data: CareReportData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{data.appName} self-care report</Text>
        <Text style={styles.subtitle}>
          {periodLabel(data.period)} · {data.startDate} to {data.endDate}
        </Text>

        <View style={styles.metaRow}>
          <Text>Prepared for {data.displayName}</Text>
          <Text>Care Score {data.overallScore}</Text>
          <Text>Completion {data.overallRate}%</Text>
        </View>

        {data.domains.map((domain) => (
          <View key={domain.name}>
            <Text style={styles.domainTitle}>
              {domain.name} · {domain.completionRate}%
            </Text>
            {domain.items.map((item) => (
              <View key={item.name} wrap={false} style={styles.item}>
                <View style={styles.row}>
                  <Text>{item.name}</Text>
                  <Text>
                    {item.completedCount}/{item.scheduledCount} done
                  </Text>
                </View>
                {item.entries.length > 0 ? (
                  <View style={styles.details}>
                    {item.entries.map((entry) => (
                      <ReportEntryLines
                        key={entry.date}
                        entry={entry}
                        showDate={data.period !== "daily"}
                      />
                    ))}
                  </View>
                ) : null}
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by {data.appName}. This report is for personal reflection.
        </Text>
      </Page>
    </Document>
  );
}
